global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'weather-proxy'
    static_configs:
      - targets: ['weather-api:8000']
    metrics_path: '/metrics'
